export const ADD_ARTICLE = "ADD_ARTICLE";
export const DATA_LOADED = "DATA_LOADED";
export const RAID_DATA_LOADED = "RAID_DATA_LOADED";
export const DATA_REQUESTED = "DATA_REQUESTED";
export const RAID_DATA_REQUESTED = "RAID_DATA_REQUESTED";
export const API_ERRORED = "API_ERRORED";
