"""empty message

Revision ID: 04e40925e9ec
Revises: c4b25814a81c
Create Date: 2020-02-15 08:58:47.202292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e40925e9ec'
down_revision = 'c4b25814a81c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raidtracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Text(), nullable=True),
    sa.Column('trackerid', sa.Text(), nullable=True),
    sa.Column('owner', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('userdata', sa.Column('userid', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userdata', 'userid')
    op.drop_table('raidtracker')
    # ### end Alembic commands ###
