"""empty message

Revision ID: 08be8b5837cd
Revises: ed4da029c28f
Create Date: 2020-01-19 10:36:22.732995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08be8b5837cd'
down_revision = 'ed4da029c28f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actiontransient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['action.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actiontransient')
    # ### end Alembic commands ###
