"""empty message

Revision ID: 266029cb083c
Revises: 
Create Date: 2020-01-16 15:02:21.987316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266029cb083c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notoriousmonster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bnpcbase', sa.Text(), nullable=True),
    sa.Column('rank', sa.SMALLINT(), nullable=True),
    sa.Column('bnpcname', sa.Text(), nullable=True),
    sa.Column('unk3', sa.SMALLINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notoriousmonster')
    # ### end Alembic commands ###
