"""empty message

Revision ID: 477a009b8688
Revises: d908253d913f
Create Date: 2020-02-08 12:19:21.309063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477a009b8688'
down_revision = 'd908253d913f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raiddrops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('classjob', sa.Text(), nullable=True),
    sa.Column('world', sa.Text(), nullable=True),
    sa.Column('isreporter', sa.Boolean(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('logmessage', sa.Text(), nullable=True),
    sa.Column('itemid', sa.Integer(), nullable=True),
    sa.Column('itemquantity', sa.SMALLINT(), nullable=True),
    sa.Column('playerid', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raiddrops')
    # ### end Alembic commands ###
