"""empty message

Revision ID: 5609a06053b7
Revises: d46ac2f8780c
Create Date: 2020-02-15 12:59:19.852597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5609a06053b7'
down_revision = 'd46ac2f8780c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raidtracker', sa.Column('raidname', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raidtracker', 'raidname')
    # ### end Alembic commands ###
