"""empty message

Revision ID: 5620ea769782
Revises: ccbf5271f472
Create Date: 2021-05-24 18:46:49.082353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5620ea769782'
down_revision = 'ccbf5271f472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raidcalendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Text(), nullable=True),
    sa.Column('raidid', sa.Text(), nullable=True),
    sa.Column('calendarid', sa.Text(), nullable=True),
    sa.Column('owner', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('day', sa.SMALLINT(), nullable=True),
    sa.Column('starttime', sa.Time(), nullable=True),
    sa.Column('endtime', sa.Time(), nullable=True),
    sa.Column('isstandard', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raidcalendar')
    # ### end Alembic commands ###
