"""empty message

Revision ID: 5a4929da811c
Revises: 5609a06053b7
Create Date: 2020-02-19 10:43:06.121613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a4929da811c'
down_revision = '5609a06053b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipetemp')
    op.add_column('item', sa.Column('unk36', sa.SMALLINT(), nullable=True))
    op.add_column('item', sa.Column('unk41', sa.SMALLINT(), nullable=True))
    op.add_column('item', sa.Column('unk50', sa.SMALLINT(), nullable=True))
    op.add_column('item', sa.Column('unk54', sa.SMALLINT(), nullable=True))
    op.add_column('item', sa.Column('unk89', sa.SMALLINT(), nullable=True))
    op.drop_column('item', 'unk88')
    op.drop_column('item', 'unk49')
    op.drop_column('item', 'unk40')
    op.drop_column('item', 'unk53')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('unk53', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('unk40', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('unk49', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('unk88', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_column('item', 'unk89')
    op.drop_column('item', 'unk54')
    op.drop_column('item', 'unk50')
    op.drop_column('item', 'unk41')
    op.drop_column('item', 'unk36')
    op.create_table('recipetemp',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('crafttype', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recipeleveltable', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemresult', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amountresult', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemingredient0', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amountingredient0', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemingredient1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amountingredient1', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemingredient2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amountingredient2', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemingredient3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amountingredient3', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemingredient4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amountingredient4', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemingredient5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amountingredient5', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemingredient6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amountingredient6', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemingredient7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amountingredient7', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemingredient8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amountingredient8', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemingredient9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amountingredient9', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('unk25', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('issecondary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('materialqualityfactor', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('difficultyfactor', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('qualityfactor', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('durabilityfactor', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('unk31', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('requiredcraftsmanship', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('requiredcontrol', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('quicksynthcraftsmanship', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('quicksynthcontrol', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('secretrecipebook', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('canquicksynth', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('canhq', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('exprewarded', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('statusrequired', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('itemrequired', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('isspecializationrequired', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('unk43', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('patchnumber', sa.SMALLINT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
