"""empty message

Revision ID: 8a60cf7d738c
Revises: 477a009b8688
Create Date: 2020-02-12 15:40:40.259554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a60cf7d738c'
down_revision = '477a009b8688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('raidid', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('raidname', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('pwhash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
