"""empty message

Revision ID: 960ff3fbc551
Revises: fa5cd6eeec87
Create Date: 2020-01-17 16:43:36.664225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '960ff3fbc551'
down_revision = 'fa5cd6eeec87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('actioncategory', sa.Text(), nullable=True),
    sa.Column('classjob', sa.Text(), nullable=True),
    sa.Column('behaviourtype', sa.SMALLINT(), nullable=True),
    sa.Column('classjoblevel', sa.SMALLINT(), nullable=True),
    sa.Column('isroleaction', sa.Boolean(), nullable=True),
    sa.Column('range', sa.SMALLINT(), nullable=True),
    sa.Column('cantargetself', sa.Boolean(), nullable=True),
    sa.Column('cantargetparty', sa.Boolean(), nullable=True),
    sa.Column('cantargetfriendly', sa.Boolean(), nullable=True),
    sa.Column('cantargethostile', sa.Boolean(), nullable=True),
    sa.Column('targetarea', sa.Boolean(), nullable=True),
    sa.Column('cantargetdead', sa.Boolean(), nullable=True),
    sa.Column('casttype', sa.SMALLINT(), nullable=True),
    sa.Column('effectrange', sa.SMALLINT(), nullable=True),
    sa.Column('xaxismodifier', sa.SMALLINT(), nullable=True),
    sa.Column('primarycosttype', sa.SMALLINT(), nullable=True),
    sa.Column('primarycostvalue', sa.SMALLINT(), nullable=True),
    sa.Column('secondarycosttype', sa.SMALLINT(), nullable=True),
    sa.Column('secondarycostvalue', sa.Text(), nullable=True),
    sa.Column('actioncombo', sa.Text(), nullable=True),
    sa.Column('preservescombo', sa.Boolean(), nullable=True),
    sa.Column('cast100ms', sa.SMALLINT(), nullable=True),
    sa.Column('recast100ms', sa.SMALLINT(), nullable=True),
    sa.Column('cooldowngroup', sa.SMALLINT(), nullable=True),
    sa.Column('maxcharges', sa.SMALLINT(), nullable=True),
    sa.Column('attacktype', sa.Text(), nullable=True),
    sa.Column('aspect', sa.SMALLINT(), nullable=True),
    sa.Column('actionprocstatus', sa.Text(), nullable=True),
    sa.Column('statusgainself', sa.Text(), nullable=True),
    sa.Column('unlocklink', sa.Text(), nullable=True),
    sa.Column('classjobcategory', sa.Text(), nullable=True),
    sa.Column('affectsposition', sa.Boolean(), nullable=True),
    sa.Column('omen', sa.Text(), nullable=True),
    sa.Column('ispvp', sa.Boolean(), nullable=True),
    sa.Column('isplayeraction', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action')
    # ### end Alembic commands ###
