"""empty message

Revision ID: 9719ddf1a4e5
Revises: 0f151d05df17
Create Date: 2020-02-23 19:35:03.228908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9719ddf1a4e5'
down_revision = '0f151d05df17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raidtracker', sa.Column('trackerpw', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raidtracker', 'trackerpw')
    # ### end Alembic commands ###
