"""empty message

Revision ID: 99d7c2f427c8
Revises: 9719ddf1a4e5
Create Date: 2020-02-24 20:16:52.016402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d7c2f427c8'
down_revision = '9719ddf1a4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raiddrops', sa.Column('view', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raiddrops', 'view')
    # ### end Alembic commands ###
