"""empty message

Revision ID: c4b25814a81c
Revises: dadec3d6230a
Create Date: 2020-02-14 09:51:16.192026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b25814a81c'
down_revision = 'dadec3d6230a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('raidid', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('raidname', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('pwhash', sa.Text(), nullable=True),
    sa.Column('refresh', sa.Text(), nullable=True),
    sa.Column('expires', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userdata')
    # ### end Alembic commands ###
