"""empty message

Revision ID: daa0ecadef13
Revises: 99d7c2f427c8
Create Date: 2020-03-05 11:59:55.218213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa0ecadef13'
down_revision = '99d7c2f427c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raidtracker', sa.Column('raidtype', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raidtracker', 'raidtype')
    # ### end Alembic commands ###
