"""empty message

Revision ID: dc40c2198f49
Revises: e0993511e9f6
Create Date: 2020-02-19 11:08:03.513368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc40c2198f49'
down_revision = 'e0993511e9f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actiontemp')
    op.drop_table('notoriousmonstertemp')
    op.drop_table('itemtemp')
    op.drop_table('recipelookuptemp')
    op.drop_table('actiontransienttemp')
    op.drop_table('recipetemp')
    op.add_column('action', sa.Column('actiontimelinehit', sa.Text(), nullable=True))
    op.add_column('action', sa.Column('animationend', sa.Text(), nullable=True))
    op.add_column('action', sa.Column('animationstart', sa.Text(), nullable=True))
    op.add_column('action', sa.Column('unk1', sa.Text(), nullable=True))
    op.add_column('action', sa.Column('unk19', sa.Boolean(), nullable=True))
    op.add_column('action', sa.Column('unk20', sa.Text(), nullable=True))
    op.add_column('action', sa.Column('unk22', sa.Boolean(), nullable=True))
    op.add_column('action', sa.Column('unk23', sa.Boolean(), nullable=True))
    op.add_column('action', sa.Column('unk24', sa.SMALLINT(), nullable=True))
    op.add_column('action', sa.Column('unk26', sa.Boolean(), nullable=True))
    op.add_column('action', sa.Column('unk30', sa.Boolean(), nullable=True))
    op.add_column('action', sa.Column('unk4', sa.SMALLINT(), nullable=True))
    op.add_column('action', sa.Column('unk40', sa.SMALLINT(), nullable=True))
    op.add_column('action', sa.Column('unk45', sa.SMALLINT(), nullable=True))
    op.add_column('action', sa.Column('unk49', sa.SMALLINT(), nullable=True))
    op.add_column('action', sa.Column('unk50', sa.Boolean(), nullable=True))
    op.add_column('action', sa.Column('unk54', sa.Boolean(), nullable=True))
    op.add_column('action', sa.Column('unk55', sa.Boolean(), nullable=True))
    op.add_column('action', sa.Column('unk56', sa.Boolean(), nullable=True))
    op.add_column('action', sa.Column('unk57', sa.Boolean(), nullable=True))
    op.add_column('action', sa.Column('unk58', sa.Boolean(), nullable=True))
    op.add_column('action', sa.Column('unk59', sa.Boolean(), nullable=True))
    op.add_column('action', sa.Column('unk60', sa.Boolean(), nullable=True))
    op.add_column('action', sa.Column('unk61', sa.Boolean(), nullable=True))
    op.add_column('action', sa.Column('unk62', sa.SMALLINT(), nullable=True))
    op.add_column('action', sa.Column('unk63', sa.Boolean(), nullable=True))
    op.add_column('action', sa.Column('unk64', sa.Boolean(), nullable=True))
    op.add_column('action', sa.Column('unk9', sa.SMALLINT(), nullable=True))
    op.add_column('action', sa.Column('vfx', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action', 'vfx')
    op.drop_column('action', 'unk9')
    op.drop_column('action', 'unk64')
    op.drop_column('action', 'unk63')
    op.drop_column('action', 'unk62')
    op.drop_column('action', 'unk61')
    op.drop_column('action', 'unk60')
    op.drop_column('action', 'unk59')
    op.drop_column('action', 'unk58')
    op.drop_column('action', 'unk57')
    op.drop_column('action', 'unk56')
    op.drop_column('action', 'unk55')
    op.drop_column('action', 'unk54')
    op.drop_column('action', 'unk50')
    op.drop_column('action', 'unk49')
    op.drop_column('action', 'unk45')
    op.drop_column('action', 'unk40')
    op.drop_column('action', 'unk4')
    op.drop_column('action', 'unk30')
    op.drop_column('action', 'unk26')
    op.drop_column('action', 'unk24')
    op.drop_column('action', 'unk23')
    op.drop_column('action', 'unk22')
    op.drop_column('action', 'unk20')
    op.drop_column('action', 'unk19')
    op.drop_column('action', 'unk1')
    op.drop_column('action', 'animationstart')
    op.drop_column('action', 'animationend')
    op.drop_column('action', 'actiontimelinehit')
    op.create_table('recipetemp',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('crafttype', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recipeleveltable', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemresult', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amountresult', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemingredient0', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amountingredient0', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemingredient1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amountingredient1', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemingredient2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amountingredient2', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemingredient3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amountingredient3', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemingredient4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amountingredient4', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemingredient5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amountingredient5', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemingredient6', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amountingredient6', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemingredient7', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amountingredient7', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemingredient8', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amountingredient8', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemingredient9', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amountingredient9', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('unk25', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('issecondary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('materialqualityfactor', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('difficultyfactor', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('qualityfactor', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('durabilityfactor', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('unk31', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('requiredcraftsmanship', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('requiredcontrol', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('quicksynthcraftsmanship', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('quicksynthcontrol', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('secretrecipebook', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('canquicksynth', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('canhq', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('exprewarded', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('statusrequired', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('itemrequired', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('isspecializationrequired', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('unk43', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('patchnumber', sa.SMALLINT(), autoincrement=False, nullable=True)
    )
    op.create_table('actiontransienttemp',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('recipelookuptemp',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unk0', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unk1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unk2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unk3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unk4', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unk5', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unk6', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unk7', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('itemtemp',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('singular', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('adjective', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plural', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('possessivepronoun', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('startswithvowel', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('unk5', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('pronoun', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('article', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('icon', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('levelitem', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('rarity', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('filtergroup', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('additionaldata', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('itemuicategory', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('itemsearchcategory', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('equipslotcategory', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('unk18', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stacksize', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('isunique', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('isuntradable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('isindisposable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pricemid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pricelow', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('canbehq', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('isdyeable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('iscrestworthy', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('itemaction', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('unk30', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('cooldowns', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('classjobrepair', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('itemrepair', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('itemglamour', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('salvage', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('iscollectable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('alwayscollectable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('aetherialreduce', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('levelequip', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('equiprestriction', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('classjobcategory', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('grandcompany', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('itemseries', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparammodifier', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('modelmain', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('modelsub', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('classjobuse', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('damagephys', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('damagemag', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('delayms', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('blockrate', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('block', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('defensephys', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('defensemag', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparam0', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvalue0', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparam1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvalue1', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparam2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvalue2', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparam3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvalue3', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparam4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvalue4', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparam5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvalue5', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemspecialbonus', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('itemspecialbonusparam', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparamspecial0', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvaluespecial0', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparamspecial1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvaluespecial1', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparamspecial2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvaluespecial2', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparamspecial3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvaluespecial3', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparamspecial4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvaluespecial4', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparamspecial5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvaluespecial5', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('materializetype', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('materiaslotcount', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('isadvancedmeldingpermitted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ispvp', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('isglamourous', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('iscraftable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('craftid', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('unk36', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('unk41', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('unk50', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('unk54', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('unk89', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('lot', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.create_table('notoriousmonstertemp',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bnpcbase', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rank', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('bnpcname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unk3', sa.SMALLINT(), autoincrement=False, nullable=True)
    )
    op.create_table('actiontemp',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('icon', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actioncategory', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('classjob', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('behaviourtype', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('classjoblevel', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('isroleaction', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('range', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('cantargetself', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cantargetparty', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cantargetfriendly', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cantargethostile', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('targetarea', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cantargetdead', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('casttype', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('effectrange', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('xaxismodifier', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('primarycosttype', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('primarycostvalue', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('secondarycosttype', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('secondarycostvalue', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actioncombo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preservescombo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cast100ms', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('recast100ms', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('cooldowngroup', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('maxcharges', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('attacktype', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('aspect', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('actionprocstatus', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('statusgainself', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unlocklink', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('classjobcategory', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('affectsposition', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('omen', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ispvp', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('isplayeraction', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
