"""empty message

Revision ID: e0993511e9f6
Revises: 5a4929da811c
Create Date: 2020-02-19 10:46:16.214602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0993511e9f6'
down_revision = '5a4929da811c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actiontemp')
    op.drop_table('actiontransienttemp')
    op.drop_table('itemtemp')
    op.add_column('item', sa.Column('lot', sa.Boolean(), nullable=True))
    op.drop_column('item', 'isequippable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('isequippable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('item', 'lot')
    op.create_table('itemtemp',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('singular', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('adjective', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plural', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('possessivepronoun', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('startswithvowel', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('unk5', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('pronoun', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('article', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('icon', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('levelitem', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('rarity', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('filtergroup', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('additionaldata', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('itemuicategory', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('itemsearchcategory', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('equipslotcategory', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('unk18', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stacksize', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('isunique', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('isuntradable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('isindisposable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('isequippable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('pricemid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pricelow', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('canbehq', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('isdyeable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('iscrestworthy', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('itemaction', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('unk30', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('cooldowns', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('classjobrepair', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('itemrepair', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('itemglamour', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('salvage', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('iscollectable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('alwayscollectable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('aetherialreduce', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('levelequip', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('equiprestriction', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('classjobcategory', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('grandcompany', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('itemseries', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparammodifier', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('modelmain', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('modelsub', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('classjobuse', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('damagephys', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('damagemag', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('delayms', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('blockrate', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('block', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('defensephys', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('defensemag', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparam0', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvalue0', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparam1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvalue1', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparam2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvalue2', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparam3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvalue3', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparam4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvalue4', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparam5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvalue5', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('itemspecialbonus', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('itemspecialbonusparam', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparamspecial0', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvaluespecial0', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparamspecial1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvaluespecial1', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparamspecial2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvaluespecial2', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparamspecial3', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvaluespecial3', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparamspecial4', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvaluespecial4', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('baseparamspecial5', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('baseparamvaluespecial5', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('materializetype', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('materiaslotcount', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('isadvancedmeldingpermitted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ispvp', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('isglamourous', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('iscraftable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('craftid', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('unk36', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('unk41', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('unk50', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('unk54', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('unk89', sa.SMALLINT(), autoincrement=False, nullable=True)
    )
    op.create_table('actiontransienttemp',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('actiontemp',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('icon', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actioncategory', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('classjob', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('behaviourtype', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('classjoblevel', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('isroleaction', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('range', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('cantargetself', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cantargetparty', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cantargetfriendly', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cantargethostile', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('targetarea', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cantargetdead', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('casttype', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('effectrange', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('xaxismodifier', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('primarycosttype', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('primarycostvalue', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('secondarycosttype', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('secondarycostvalue', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actioncombo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preservescombo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('cast100ms', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('recast100ms', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('cooldowngroup', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('maxcharges', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('attacktype', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('aspect', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('actionprocstatus', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('statusgainself', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unlocklink', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('classjobcategory', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('affectsposition', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('omen', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ispvp', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('isplayeraction', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
