"""empty message

Revision ID: ed8992b98faa
Revises: 4fc34de0729e
Create Date: 2020-01-17 15:21:58.674428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed8992b98faa'
down_revision = '4fc34de0729e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('actiontransient', sa.Column('idf', sa.Integer(), nullable=False))
    #op.create_foreign_key(None, 'actiontransient', 'action', ['idf'], ['id'])
    # ### end Alembic commands ###
    return

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actiontransient', type_='foreignkey')
    op.drop_column('actiontransient', 'idf')
    # ### end Alembic commands ###
