"""empty message

Revision ID: fa5cd6eeec87
Revises: ed8992b98faa
Create Date: 2020-01-17 15:25:20.017929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5cd6eeec87'
down_revision = 'ed8992b98faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actiontransient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idf', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['idf'], ['action.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actiontransient')
    # ### end Alembic commands ###
