"""empty message

Revision ID: fd20afbb1aea
Revises: d46ac2f8780c
Create Date: 2020-02-15 20:55:59.397648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd20afbb1aea'
down_revision = 'dc40c2198f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raidtracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Text(), nullable=True),
    sa.Column('raidname', sa.Text(), nullable=True),
    sa.Column('trackerid', sa.Text(), nullable=True),
    sa.Column('owner', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('isactive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('raidid', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('raidname', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('pwhash', sa.Text(), nullable=True),
    sa.Column('refresh', sa.Text(), nullable=True),
    sa.Column('expires', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userdata')
    op.drop_table('raidtracker')
    # ### end Alembic commands ###
