from marshmallow import fields, Schema
from . import db

class ItemModel(db.Model):
    __tablename__ = 'item'

    id = db.Column(db.Integer, primary_key=True)
    singular = db.Column(db.Text)
    adjective = db.Column(db.Integer)
    plural = db.Column(db.Text)
    possessivepronoun = db.Column(db.SMALLINT)
    startswithvowel = db.Column(db.SMALLINT)
    unk5 = db.Column(db.SMALLINT)
    pronoun = db.Column(db.SMALLINT)
    article = db.Column(db.SMALLINT)
    description = db.Column(db.Text)
    name = db.Column(db.Text)
    icon = db.Column(db.Text)
    levelitem = db.Column(db.SMALLINT)
    rarity = db.Column(db.SMALLINT)
    filtergroup = db.Column(db.SMALLINT)
    additionaldata = db.Column(db.Text)
    itemuicategory = db.Column(db.Text)
    itemsearchcategory = db.Column(db.Text)
    equipslotcategory = db.Column(db.SMALLINT)
    unk18 = db.Column(db.Integer)
    stacksize = db.Column(db.Integer)
    isunique = db.Column(db.Boolean)
    isuntradable = db.Column(db.Boolean)
    isindisposable = db.Column(db.Boolean)
    isequippable = db.Column(db.Boolean)
    pricemid = db.Column(db.Integer)
    pricelow = db.Column(db.Integer)
    canbehq = db.Column(db.Boolean)
    isdyeable = db.Column(db.Boolean)
    iscrestworthy = db.Column(db.Boolean)
    itemaction = db.Column(db.SMALLINT)
    unk30 = db.Column(db.SMALLINT)
    cooldowns = db.Column(db.SMALLINT)
    classjobrepair = db.Column(db.Text)
    itemrepair = db.Column(db.Text)
    itemglamour = db.Column(db.Text)
    salvage = db.Column(db.SMALLINT)
    iscollectable = db.Column(db.Boolean)
    alwayscollectable = db.Column(db.Boolean)
    aetherialreduce = db.Column(db.SMALLINT)
    levelequip = db.Column(db.SMALLINT)
    unk40 = db.Column(db.SMALLINT)
    equiprestriction = db.Column(db.SMALLINT)
    classjobcategory = db.Column(db.Text)
    grandcompany = db.Column(db.Text)
    itemseries = db.Column(db.Text)
    baseparammodifier = db.Column(db.SMALLINT)
    modelmain = db.Column(db.ARRAY(db.Integer))
    modelsub = db.Column(db.ARRAY(db.Integer))
    classjobuse = db.Column(db.Text)
    unk49 = db.Column(db.SMALLINT)
    damagephys = db.Column(db.SMALLINT)
    damagemag = db.Column(db.SMALLINT)
    delayms = db.Column(db.SMALLINT)
    unk53 = db.Column(db.SMALLINT)
    blockrate = db.Column(db.SMALLINT)
    block = db.Column(db.SMALLINT)
    defensephys = db.Column(db.SMALLINT)
    defensemag = db.Column(db.SMALLINT)
    baseparam0 = db.Column(db.Text)
    baseparamvalue0 = db.Column(db.SMALLINT)
    baseparam1 = db.Column(db.Text)
    baseparamvalue1 = db.Column(db.SMALLINT)
    baseparam2 = db.Column(db.Text)
    baseparamvalue2 = db.Column(db.SMALLINT)
    baseparam3 = db.Column(db.Text)
    baseparamvalue3 = db.Column(db.SMALLINT)
    baseparam4 = db.Column(db.Text)
    baseparamvalue4 = db.Column(db.SMALLINT)
    baseparam5 = db.Column(db.Text)
    baseparamvalue5 = db.Column(db.SMALLINT)
    itemspecialbonus = db.Column(db.Text)
    itemspecialbonusparam = db.Column(db.SMALLINT)
    baseparamspecial0 = db.Column(db.Text)
    baseparamvaluespecial0 = db.Column(db.SMALLINT)
    baseparamspecial1 = db.Column(db.Text)
    baseparamvaluespecial1 = db.Column(db.SMALLINT)
    baseparamspecial2 = db.Column(db.Text)
    baseparamvaluespecial2 = db.Column(db.SMALLINT)
    baseparamspecial3 = db.Column(db.Text)
    baseparamvaluespecial3 = db.Column(db.SMALLINT)
    baseparamspecial4 = db.Column(db.Text)
    baseparamvaluespecial4 = db.Column(db.SMALLINT)
    baseparamspecial5 = db.Column(db.Text)
    baseparamvaluespecial5 = db.Column(db.SMALLINT)
    materializetype = db.Column(db.SMALLINT)
    materiaslotcount = db.Column(db.SMALLINT)
    isadvancedmeldingpermitted = db.Column(db.Boolean)
    ispvp = db.Column(db.Boolean)
    unk88 = db.Column(db.SMALLINT)
    isglamourous = db.Column(db.Boolean)

    def __init__(self,data):
        self.id = data.get(id)
        self.singular = data.get(singular)
        self.adjective = data.get(adjective)
        self.plural = data.get(plural)
        self.possessivepronoun = data.get(possessivepronoun)
        self.startswithvowel = data.get(startswithvowel)
        self.unk5 = data.get(unk5)
        self.pronoun = data.get(pronoun)
        self.article = data.get(article)
        self.description = data.get(description)
        self.name = data.get(name)
        self.icon = data.get(icon)
        self.levelitem = data.get(levelitem)
        self.rarity = data.get(rarity)
        self.filtergroup = data.get(filtergroup)
        self.additionaldata = data.get(additionaldata)
        self.itemuicategory = data.get(itemuicategory)
        self.itemsearchcategory = data.get(itemsearchcategory)
        self.equipslotcategory = data.get(equipslotcategory)
        self.unk18 = data.get(unk18)
        self.stacksize = data.get(stacksize)
        self.isunique = data.get(isunique)
        self.isuntradable = data.get(isuntradable)
        self.isindisposable = data.get(isindisposable)
        self.isequippable = data.get(isequippable)
        self.pricemid = data.get(pricemid)
        self.pricelow = data.get(pricelow)
        self.canbehq = data.get(canbehq)
        self.isdyeable = data.get(isdyeable)
        self.iscrestworthy = data.get(iscrestworthy)
        self.itemaction = data.get(itemaction)
        self.unk30 = data.get(unk30)
        self.cooldowns = data.get(cooldowns)
        self.classjobrepair = data.get(classjobrepair)
        self.itemrepair = data.get(itemrepair)
        self.itemglamour = data.get(itemglamour)
        self.salvage = data.get(salvage)
        self.iscollectable = data.get(iscollectable)
        self.alwayscollectable = data.get(alwayscollectable)
        self.aetherialreduce = data.get(aetherialreduce)
        self.levelequip = data.get(levelequip)
        self.unk40 = data.get(unk40)
        self.equiprestriction = data.get(equiprestriction)
        self.classjobcategory = data.get(classjobcategory)
        self.grandcompany = data.get(grandcompany)
        self.itemseries = data.get(itemseries)
        self.baseparammodifier = data.get(baseparammodifier)
        self.modelmain = data.get(modelmain)
        self.modelsub = data.get(modelsub)
        self.classjobuse = data.get(classjobuse)
        self.unk49 = data.get(unk49)
        self.damagephys = data.get(damagephys)
        self.damagemag = data.get(damagemag)
        self.delayms = data.get(delayms)
        self.unk53 = data.get(unk53)
        self.blockrate = data.get(blockrate)
        self.block = data.get(block)
        self.defensephys = data.get(defensephys)
        self.defensemag = data.get(defensemag)
        self.baseparam0 = data.get(baseparam0)
        self.baseparamvalue0 = data.get(baseparamvalue0)
        self.baseparam1 = data.get(baseparam1)
        self.baseparamvalue1 = data.get(baseparamvalue1)
        self.baseparam2 = data.get(baseparam2)
        self.baseparamvalue2 = data.get(baseparamvalue2)
        self.baseparam3 = data.get(baseparam3)
        self.baseparamvalue3 = data.get(baseparamvalue3)
        self.baseparam4 = data.get(baseparam4)
        self.baseparamvalue4 = data.get(baseparamvalue4)
        self.baseparam5 = data.get(baseparam5)
        self.baseparamvalue5 = data.get(baseparamvalue5)
        self.itemspecialbonus = data.get(itemspecialbonus)
        self.itemspecialbonusparam = data.get(itemspecialbonusparam)
        self.baseparamspecial0 = data.get(baseparamspecial0)
        self.baseparamvaluespecial0 = data.get(baseparamvaluespecial0)
        self.baseparamspecial1 = data.get(baseparamspecial1)
        self.baseparamvaluespecial1 = data.get(baseparamvaluespecial1)
        self.baseparamspecial2 = data.get(baseparamspecial2)
        self.baseparamvaluespecial2 = data.get(baseparamvaluespecial2)
        self.baseparamspecial3 = data.get(baseparamspecial3)
        self.baseparamvaluespecial3 = data.get(baseparamvaluespecial3)
        self.baseparamspecial4 = data.get(baseparamspecial4)
        self.baseparamvaluespecial4 = data.get(baseparamvaluespecial4)
        self.baseparamspecial5 = data.get(baseparamspecial5)
        self.baseparamvaluespecial5 = data.get(baseparamvaluespecial5)
        self.materializetype = data.get(materializetype)
        self.materiaslotcount = data.get(materiaslotcount)
        self.isadvancedmeldingpermitted = data.get(isadvancedmeldingpermitted)
        self.ispvp = data.get(ispvp)
        self.unk88 = data.get(unk88)
        self.isglamourous = data.get(isglamourous)

    def save(self):
        db.session.add(self)
        db.session.commit()

    def update(self, data):
        for key, item in data.items():
            setattr(self, key, item)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    @staticmethod
    def get_limit(n):
        return ItemModel.query.limit(n).all()

    def get_one(id):
        return ItemModel.query.get(id)

    def __repr(self):
        return '<id {}>'.format(self.id)


class ItemSchema(Schema):
    id = fields.Int(dump_only=True)
    singular = fields.Str(required=True)
    adjective = fields.Int(required=True)
    plural = fields.Str(required=True)
    possessivepronoun = fields.Int(required=True)
    startswithvowel = fields.Int(required=True)
    unk5 = fields.Int(required=True)
    pronoun = fields.Int(required=True)
    article = fields.Int(required=True)
    description = fields.Str(required=True)
    name = fields.Str(required=True)
    icon = fields.Str(required=True)
    levelitem = fields.Int(required=True)
    rarity = fields.Int(required=True)
    filtergroup = fields.Int(required=True)
    additionaldata = fields.Str(required=True)
    itemuicategory = fields.Str(required=True)
    itemsearchcategory = fields.Str(required=True)
    equipslotcategory = fields.Int(required=True)
    unk18 = fields.Int(required=True)
    stacksize = fields.Int(required=True)
    isunique = fields.Boolean(required=True)
    isuntradable = fields.Boolean(required=True)
    isindisposable = fields.Boolean(required=True)
    isequippable = fields.Boolean(required=True)
    pricemid = fields.Int(required=True)
    pricelow = fields.Int(required=True)
    canbehq = fields.Int(required=True)
    isdyeable = fields.Boolean(required=True)
    iscrestworthy = fields.Boolean(required=True)
    itemaction = fields.Int(required=True)
    unk30 = fields.Int(required=True)
    cooldowns = fields.Int(required=True)
    classjobrepair = fields.Str(required=True)
    itemrepair = fields.Str(required=True)
    itemglamour = fields.Str(required=True)
    salvage = fields.Int(required=True)
    iscollectable = fields.Boolean(required=True)
    alwayscollectable = fields.Boolean(required=True)
    aetherialreduce = fields.Int(required=True)
    levelequip = fields.Int(required=True)
    unk40 = fields.Int(required=True)
    equiprestriction = fields.Int(required=True)
    classjobcategory = fields.Str(required=True)
    grandcompany = fields.Str(required=True)
    itemseries = fields.Str(required=True)
    baseparammodifier = fields.Int(required=True)
    modelmain = fields.List(fields.Int(), required=True)
    modelsub = fields.List(fields.Int(), required=True)
    classjobuse = fields.Str(required=True)
    unk49 = fields.Int(required=True)
    damagephys = fields.Int(required=True)
    damagemag = fields.Int(required=True)
    delayms = fields.Int(required=True)
    unk53 = fields.Int(required=True)
    blockrate = fields.Int(required=True)
    block = fields.Int(required=True)
    defensephys = fields.Int(required=True)
    defensemag = fields.Int(required=True)
    baseparam0 = fields.Str(required=True)
    baseparamvalue0 = fields.Int(required=True)
    baseparam1 = fields.Str(required=True)
    baseparamvalue1 = fields.Int(required=True)
    baseparam2 = fields.Str(required=True)
    baseparamvalue2 = fields.Int(required=True)
    baseparam3 = fields.Str(required=True)
    baseparamvalue3 = fields.Int(required=True)
    baseparam4 = fields.Str(required=True)
    baseparamvalue4 = fields.Int(required=True)
    baseparam5 = fields.Str(required=True)
    baseparamvalue5 = fields.Int(required=True)
    itemspecialbonus = fields.Str(required=True)
    itemspecialbonusparam = fields.Int(required=True)
    baseparamspecial0 = fields.Str(required=True)
    baseparamvaluespecial0 = fields.Int(required=True)
    baseparamspecial1 = fields.Str(required=True)
    baseparamvaluespecial1 = fields.Int(required=True)
    baseparamspecial2 = fields.Str(required=True)
    baseparamvaluespecial2 = fields.Int(required=True)
    baseparamspecial3 = fields.Str(required=True)
    baseparamvaluespecial3 = fields.Int(required=True)
    baseparamspecial4 = fields.Str(required=True)
    baseparamvaluespecial4 = fields.Int(required=True)
    baseparamspecial5 = fields.Str(required=True)
    baseparamvaluespecial5 = fields.Int(required=True)
    materializetype = fields.Int(required=True)
    materiaslotcount = fields.Int(required=True)
    isadvancedmeldingpermitted = fields.Boolean(required=True)
    ispvp = fields.Boolean(required=True)
    unk88 = fields.Int(required=True)
    isglamourous = fields.Boolean(required=True)
